Account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('index', views.index, name='index'),
    path('transfer', views.transfer, name='transfer'),
    path('show/<str:id>', views.show, name='show'),
]

Transfer/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Account.urls', namespace='account'))
]

Account/models.py
from django.db import models

# Create your models here.
class Account(models.Model):
    account_id = models.CharField(max_length=64, blank=False, null=False)
    username   = models.CharField(max_length=256, blank=False, null=False)
    balance    = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f"{self.account_id} - {self.balance}"

Account/views.py
from .models import Account
from django.db.models import Sum
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    accounts = Account.objects.all()
    try:
        if len(accounts == 0):
            return render(request, '400.html')
    except Exception:
        return render(request, '400.html')
    accounts_sum = round(sum(Account.objects.values_list('balance', flat=True)))
    return render(request, 'index.html', {'accounts': accounts, 'accounts_sum': accounts_sum})

@csrf_exempt
def transfer(request):
    if request.method == 'POST':
        from_id = request.POST.get('source_account_id')
        account_id = request.POST.get('target_account_id')
        amount = float(request.POST.get('amount'))

        if round(amount) == 0:
            return JsonResponse({'success': False, 'message': 'You must enter a number.'})

        from_account = Account.objects.get(id=from_id)
        from_account_balance = from_account.balance
        if from_account_balance < amount:
            return JsonResponse({'success': False, 'message': 'Enter a valide balance.'})
        
        try:
            account = Account.objects.get(id=account_id)
            account.balance += amount
            account.save()

            from_account.balance -= amount
            from_account.save()

            return JsonResponse({'success': True, 'message': 'Transfer completed successfully.'})
        except Account.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Account not found.'})
        except Exception as e:
            return JsonResponse({'success': False, 'message': str(e)})
    return JsonResponse({'success': False, 'message': 'Invalid request method.'})
    
def show(request, id):
    return render(request, 'show.html', {'account': Account.objects.get(account_id=id)})

templates/_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <!-- CSS -->
    <link href="{% static 'vendor/pg-calendar/css/pignose.calendar.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/chartist/css/chartist.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/datatables/css/jquery.dataTables.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/sweetalert2/dist/sweetalert2.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block cus_css %}{% endblock %}
</head>

<body>
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>

    <div id="main-wrapper">

        <div class="nav-header">
            <a href="" class="brand-logo">
                <img class="logo-abbr" src="{% static 'images/logo.png' %}" alt="">
                <img class="logo-compact" src="{% static 'images/logo-text.png' %}" alt="">
                <img class="brand-title" src="{% static 'images/logo-text.png' %}" alt="">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>

        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="header-left">
                            <div class="search_bar dropdown">
                                <span class="search_icon p-3 c-pointer" data-toggle="dropdown">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                                <div class="dropdown-menu p-0 m-0">
                                    <form>
                                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                                    </form>
                                </div>
                            </div>
                        </div>

                        <ul class="navbar-nav header-right">
                            <li class="nav-item dropdown notification_dropdown">
                                <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                                    <i class="mdi mdi-bell"></i>
                                    <div class="pulse-css"></div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <ul class="list-unstyled">
                                        <li class="media dropdown-item">
                                            <span class="success"><i class="ti-user"></i></span>
                                            <div class="media-body">
                                                <a href="#">
                                                    <p><strong>Martin</strong> has added a <strong>customer</strong> Successfully</p>
                                                </a>
                                            </div>
                                            <span class="notify-time">3:20 am</span>
                                        </li>
                                    </ul>
                                    <a class="all-notification" href="#">See all notifications <i class="ti-arrow-right"></i></a>
                                </div>
                            </li>
                            <li class="nav-item dropdown header-profile">
                                <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                                    <i class="mdi mdi-account"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="" class="dropdown-item">
                                        <i class="icon-user"></i>
                                        <span class="ml-2">Profile</span>
                                    </a>
                                    <a href="" class="dropdown-item">
                                        <i class="icon-key"></i>
                                        <span class="ml-2">Logout</span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>

        <div class="quixnav">
            <div class="quixnav-scroll">
                <ul class="metismenu" id="menu">
                    <li class="nav-label first">Main Menu</li>
                    <li><a href=""><i class="icon icon-single-04"></i><span class="nav-text">Dashboard</span></a></li>
                </ul>
            </div>
        </div>

        <div class="content-body">
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </div>

        <div class="footer">
            <div class="copyright">
                <p>Copyright © Designed &amp; Developed by Abdelrahman S. Hussainy <backend> 2025</p>
            </div>
        </div>
    </div>

    <script src="{% static 'vendor/global/global.min.js' %}"></script>
    <script src="{% static 'js/quixnav-init.js' %}"></script>
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'vendor/chartist/js/chartist.min.js' %}"></script>
    <script src="{% static 'vendor/moment/moment.min.js' %}"></script>
    <script src="{% static 'vendor/pg-calendar/js/pignose.calendar.min.js' %}"></script>
    <script src="{% static 'js/dashboard/dashboard-2.js' %}"></script>

    <script src="{% static 'vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/plugins-init/datatables.init.js' %}"></script>

    <script src="{% static 'vendor/sweetalert2/dist/sweetalert2.min.js'%}"></script>
    <script src="{% static 'js/plugins-init/sweetalert.init.js'%}"></script>
    {% block cus_js %}{% endblock %}
</body>

</html>

templates/index.html
{% extends '_master.html' %} 
{% load static %}
{% load filters %}

{% block title %}All Accounts{% endblock %}

{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>Hi, This's the accounts' list!</h4>
            <p class="mb-0">Just open account transfer to transfer the balance.</p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="stat-widget-one card-body">
                <div class="stat-icon d-inline-block">
                    <i class="ti-user text-primary border-primary"></i>
                </div>
                <div class="stat-content d-inline-block">
                    <div class="stat-text">Number of Accounts</div>
                    <div class="stat-digit">{{ accounts|count }}</div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="stat-widget-one card-body">
                <div class="stat-icon d-inline-block">
                    <i class="ti-money text-success border-success"></i>
                </div>
                <div class="stat-content d-inline-block">
                    <div class="stat-text">Total Balance</div>
                    <div class="stat-digit">{{ accounts_sum }}</div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Basic Datatable</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example" class="display" style="width:100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Account Name</th>
                                <th>Balance</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for account in accounts %}
                                <tr>
                                    <td>{{ account.id }}</td>
                                    <td>{{ account.username }}</td>
                                    <td>{{ account.balance }}</td>
                                    <td class="text-center">
                                        <div class="button-dropdown">
                                            <div class="btn-group m-b-10">
                                                <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown">
                                                    Actions
                                                </button>
                                                <div class="dropdown-menu">
                                                    <a class="dropdown-item transfer-btn" href="#" data-toggle="modal" data-target="#transfer-modal" data-account-id="{{ account.id }}" data-account-name="{{ account.username }}">
                                                        Transfer
                                                    </a>
                                                    <a class="dropdown-item transfer-btn" href="{% url 'account:show' id=account.account_id %}">
                                                        Show Profile
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Account Name</th>
                                <th>Balance</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="transfer-modal" tabindex="-1" role="dialog" aria-labelledby="transfer-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="transfer-modal-label">Transfer From <span id="source-account-name"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="source-account-id">
                <div class="form-group">
                    <label for="target-account">Select Target Account</label>
                    <select class="form-control" id="target-account" required>
                        <option value="" disabled selected>Select an account</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="transfer-amount">Transfer Amount</label>
                    <input type="number" class="form-control" id="transfer-amount" placeholder="Enter amount" step="0.01" min="0" required>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary transfer-submit">Transfer</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block cus_js %}
<script>
    $(document).ready(function() {
        // When the transfer button is clicked, populate the modal with the relevant data
        $('.transfer-btn').on('click', function() {
            var sourceAccountId = $(this).data('account-id');
            var sourceAccountName = $(this).data('account-name');

            // Set the source account details in the modal
            $('#source-account-id').val(sourceAccountId);
            $('#source-account-name').text(sourceAccountName);

            // Clear previous options and populate the target account dropdown
            $('#target-account').empty().append('<option value="" disabled selected>Select an account</option>');
            {% for acc in accounts %}
                {% if acc.id != account.id %}
                    $('#target-account').append('<option value="{{ acc.id }}">{{ acc.username }}</option>');
                {% endif %}
            {% endfor %}
        });

        // Handle the transfer submission
        $('.transfer-submit').on('click', function() {
            var sourceAccountId = $('#source-account-id').val();
            var targetAccountId = $('#target-account').val();
            var transferAmount = $('#transfer-amount').val();

            if (!targetAccountId) {
                showSweetAlert('warning', 'Please select a target account.');
                return;
            }
            if (targetAccountId == sourceAccountId) {
                showSweetAlert('warning', 'Please select another account.');
                return;
            }
            if (!transferAmount || isNaN(transferAmount) || parseFloat(transferAmount) <= 0) {
                showSweetAlert('warning', 'Please enter a valid transfer amount.');
                return;
            }

            var data = {
                'source_account_id': sourceAccountId,
                'target_account_id': targetAccountId,
                'amount': transferAmount,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            };

            $.ajax({
                url: '{% url "account:transfer" %}',
                type: 'POST',
                data: data,
                success: function(response) {
                    if (response.success) {
                        showSweetAlert('success', 'Transfer successful!');
                        location.reload();
                    } else {
                        showSweetAlert('error', 'Transfer failed: ' + response.message);
                    }
                },
                error: function(xhr, status, error) {
                    showSweetAlert('error', 'An error occurred: ' + error);
                }
            });
        });

        // Function to display SweetAlert2 alerts
        function showSweetAlert(type, message) {
            const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer);
                    toast.addEventListener('mouseleave', Swal.resumeTimer);
                }
            });

            Toast.fire({
                icon: type,
                title: message
            });
        }
    });
</script>
{% endblock %}

templates/show.html
{% extends '_master.html' %} 
{% load static %}
{% load filters %}

{% block title %}All Accounts{% endblock %}

{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>Hi, This's the account Details!</h4>
            <p class="mb-0">Here's the whole information about this account.</p>
        </div>
    </div>
</div>

<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Profile</h4>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="card-body">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#home8">
                                <span>
                                    <i class="ti-user"></i>
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#profile8">
                                <span>
                                    <i class="ti-home"></i>
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#messages8">
                                <span>
                                    <i class="ti-money"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content tabcontent-border">
                        <div class="tab-pane fade show active" id="home8" role="tabpanel">
                            <div class="pt-4">
                                <h4>Account Name</h4>
                                <p>
                                    {{ account.username }}
                                </p>
                                
                            </div>
                        </div>
                        <div class="tab-pane fade" id="profile8" role="tabpanel">
                            <div class="pt-4">
                                <h4>Account ID</h4>
                                <p>{{ account.account_id }}
                                </p>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="messages8" role="tabpanel">
                            <div class="pt-4">
                                <h4>Account Balance</h4>
                                <p>
                                    {{ account.balance }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block cus_js %}

{% endblock %}